from django.urls import path
from .views import *

urlpatterns = [
    path('/chats', HistoryChat.as_view()),
    path('/add-chat', AddChat, name='add-chat'),
    path('/get-chat', GetChat, name='get-chat'),
    path('/reset-chat', ResetChat, name='reset-chat'),
    path('/google-search', GoogleSearchApi, name='google-search-api'),
    path('/generate-image', GenerateImage, name='generate-image'),
    path('/accept-friend', Accept_Friend, name='accept-friend'),
    path('/reject-friend', Reject_Friend, name='reject-friend'),
    path('/send-friend-request', Send_Friend_Request, name='send-friend-request'),
    path('/remove-friend', Remove_Friend, name='remove-friend'),
    path('/get-friend-list', Get_Friend_List, name='get-friend-list'),
    path('/search-user', Search_User, name='search-user'),
    path('/cancel-friend-request', Cancel_Friend_Request, name='cancel-friend-request'),
    path('/get-account-users', Get_Account_Users, name='get-account-users'),
    path('/account-init', Account_Init, name='account-init'),
    path('/add-user', Add_User, name='add-user'),
    path('/remove-user', Remove_User, name='remove-user'),
    path('/update-user', Update_User, name='update-user'),
    path('/get-assistant-id', Get_Assistant_ID, name='get-assistant-id'),
    path('/child-init', Child_Init, name='child-init'),
    path('/create-bind-otp', Create_Bind_OTP, name='create-bind-otp'),
    path('/verify-bind-otp', Verify_Bind_OTP, name='verify-bind-otp'),
    path('/get-love-notes', Get_Love_Notes, name='get-love-notes'),
    path('/add-love-note', Add_Love_Note, name='add-love-note'),
    path('/remove-love-note', Remove_Love_Note, name='remove-love-note'),
    path('/edit-love-note', Edit_Love_Note, name='edit-love-note'),
    path('/get-children', Get_Children, name='get-children'),
    path('/child-bind-status', Child_Bind_Status, name='child-bind-status'),
    path('/unbind-children-account', Unbind_Children_Account, name='unbind-children-account'),
    path('/bind-children-account', Bind_Children_Account, name='bind-children-account'),
    path('/edit-child', Edit_Child, name='edit-child'),
]
