# Generated by Django 5.2.3 on 2025-06-19 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('isUser', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parents_Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('relation', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('user_id', 'device_token')},
            },
        ),
        migrations.CreateModel(
            name='Children_Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('user_info', models.JSONField(default={'birth_date': '', 'energy_level': 0, 'gender': '', 'name': '', 'robot_color': 0, 'robot_type': 0, 'school': ''}, verbose_name='User Information')),
                ('isActive', models.BooleanField(default=True)),
                ('friend_list', models.JSONField(default={'friends': [], 'pending': [], 'requests': []}, verbose_name='Friends')),
                ('notification', models.JSONField(default={'love_notes': [], 'missions': []}, verbose_name='Notification')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companion_app.parents_accounts')),
            ],
        ),
    ]
