# Generated by Django 5.1.6 on 2025-03-06 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Personnel_Entries',
        ),
        migrations.AddField(
            model_name='chat_history',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='companion_app.user_data'),
        ),
    ]
